#!/bin/sh
#
# Entry-point that the CI should run on each commit.
#

set -euo pipefail

cd "$(dirname "$0")/.."

nix-build nix/release.nix --no-out-link
nix-build nix/release.nix -A scripts --no-out-link

links=$(nix-build nix/release.nix --no-out-link)

# push to binary cache
$(nix-build nix/release.nix -A scripts.nix-push --no-out-link) "$links"
