#!/usr/bin/env bash
#
# Entry-point that the CI should run on each commit.
#

set -euo pipefail

cd "$(dirname "$0")/.."

target=nix/release.nix
buildArgs=(
  "$target"
  --no-out-links
)

nix-build "${buildArgs[@]}"

# push to binary cache
scripts/nix-cloud-push $(nix-build "${buildArgs[@]}")
