#!/bin/sh
#
# Entry-point that the CI should run on each commit.
#

cd "$(dirname "$0")/.."

nix-build nix/release.nix --no-out-link

# push to binary cache
nix-push "$(nix-build nix/release.nix --no-out-link)"
